import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),art=resolve(root,'research/eval/target-conversion');
const read=n=>JSON.parse(readFileSync(resolve(art,n+'.json'),'utf8'));
const r=read('results'),g=read('phase-gate'),d=read('development'),h=read('historical-replay'),m=r.metrics;
const pct=x=>(x*100).toFixed(2)+'%',sec=x=>x===null?'unavailable':(x/1000).toFixed(2)+' s';
const resourceFile=resolve(root,'../fc-agent/research-target-conversion/resource-samples.json');
const resource=existsSync(resourceFile)?JSON.parse(readFileSync(resourceFile)):null;
const lines=['# Target-Bound Evidence Conversion v0.11.3 — A–X delivery','', '**'+r.decision+'**. No Claim Revision, LLM-Wiki, Thesis, Multi-Agent or UI work.','',
 '## A. Push confirmation for c2e4e18','', 'The clean complete v0.11.2 delivery c2e4e183fa197e24b222a4fb35a8b9548fe9c6fd was pushed to origin/main before implementation; remote main was independently verified with git ls-remote. Production upstream remains push-disabled. Historical artifacts and SELECTOR READY are unchanged.','',
 '## B. Pre-code post-ranking loss audit','', '14 Top-3 reachable cases / 5 strict conversions / 9 losses. '+JSON.stringify(h.counts)+'. Full preserved interpretation/parser/validator/Candidate traces are in historical-traces.json; no unvisited rank outputs are fabricated.','',
 '## C. Files changed','',
 '- research/target-conversion/REPOSITORY_AUDIT.md: offline per-case and table/text diagnosis.',
 '- research/target-conversion/research-plan.json: versioned answer-free production research requests; evaluator-only case linkage.',
 '- research/target-conversion/domain.js: existing categories and real metric/concept registry with explicit row mappings.',
 '- research/target-conversion/contract.js and three *.schema.json: ResearchIntent, TargetBoundInterpretation and Candidate binding sidecar.',
 '- research/prompts/target-bound-interpretation-v1.txt: one version of the bounded semantic-match/raw-fact prompt.',
 '- research/target-conversion/checks.js: category/concept, unit family, assertion kind, exact request dimension and known period checks.',
 '- research/target-conversion/extraction.js: exact named-clause compound literal selection and unique identical-token source whitespace copying, with source proofs.',
 '- research/target-conversion/layer.js: bounded rank 1→2→3 target conversion using frozen grounding/parsers/Validator/proposal/Candidate rules.',
 '- research/target-conversion/context.js: offline frozen workspace loading.',
 '- research/target-conversion/cli.js: offline dev, freeze registration, one real conversion-only run, receipts, progress/resume, safety and strict evaluator.',
 '- research/target-conversion/eval.js: strict primary gate, zero wrong-target and complete fixed denominators.',
 '- research/target-conversion/replay.js: unchanged historical count/trace verification.',
 '- research/target-conversion/fixtures.js, synthetic-dev.py, dev.js: independently constructed synthetic development matrix.',
 '- research/target-conversion/report.js and README.md: deterministic reporting and local workflow.',
 '- research/target-conversion-test/*.test.js and agent/test/target-conversion.test.js: offline protections and mandatory CI integration.',
 '- research/eval/target-conversion/*.json: audit, dev, pre-registration, locked results and resource/cost/push proof.',
 '- docs/target-bound-evidence-conversion-v0.11.3.md and DELIVERY.md: full measured delivery.',
 'No modifications to frozen frontend, public API contracts, retrieval, ranking, handles, grounding, SourceSupport, parsers, Validator, EvidenceProposal, Admission, Claims or existing history.','',
 '## D. ResearchIntent contract','', '`research-intent/v1`: intentId, subjectId, targetKind, targetCategory, targetMetricOrConcept, timeScope(kind/start/end), optional explicit geography/customer-label dimension, actualOrGuidance, explicitOrDerived, createdAt. Finite production categories/concepts, exact date semantics, additionalProperties=false. No values, normalized answers, expected spans/Evidence IDs or Gold. Customer labels are period-local dimensions, not persistent identities.','',
 '## E. TargetBoundInterpretation','', '`target-bound-interpretation/v1`: targetMatch supported/not_supported/ambiguous plus fact. Only supported may carry the frozen raw-fact fields; other matches require fact:null. The model proposes semantic relevance and raw explicit interpretation only. Normalization, support identity, provenance and Candidate acceptance stay deterministic.','',
 '## F. Deterministic target checks','', 'Known category/concept compatibility; requested actual/guidance and explicit/derived; known exact period window or as-of; unit family of the requested measure; source identity/hash/subject/availability. No complex semantic guessing. Explicit named-clause value ownership prevents borrowing a different metric’s literal from the same sentence. Unknown row/phrase semantics remain a restricted model proposal.','',
 '## G. Table target binding','', 'Known row/header mismatches and requested geography/customer row dimensions reject before a model call. Wrong table periods and unit families also reject first. The immutable table parser owns cell/unit/header extraction. Null raw fields are required by the prompt, not model-reconstructed table prose. Explicit disclosed cells and percentages are not analyst-derived merely because the issuer calculated them. Missing semantic metadata is not deterministically invented.','',
 '## H. Text target binding','', 'One supplied sentence stays unchanged. The model must answer the requested measure, not another financial fact. Percentage growth cannot become a dollar change; customer revenue share cannot become receivables concentration. Unique identical-token source whitespace binding copies actual PDF line breaks; digits, dates, words and scales are never changed. All resulting raw fields still pass frozen exact-source parsing/validation.','',
 '## I. Compound literal handling','', '`exact-local-extraction/v1` can choose one literal only when an explicit named local clause uniquely binds the requested concept to that literal and its unit is source-bound. A proof records exact quote, anchor, offsets and support/hash. Respectively alignment, shared missing scales, unknown semantic anchors and ambiguous periods abstain. Joint three/six-month sensitivity remains constrained by the immutable parser and numeric risk-disclosure Validator; no coercion to actual.','',
 '## J. Dev fixtures','',`${d.cases} independent deterministic cases, passed=${d.passed}; no Qwen/embedding calls or real smoke. `+d.rows.map(x=>x.name).join(', ')+'.','',
 '## K. Historical replay','', 'Historical strict 5/16, generic 11/16, valid-but-wrong-target 6/16, post-ranking loss 9 among 14 reachable. Replay preserves old attempts and decisions verbatim; new rules do not retroactively count conversions.','',
 '## L. Locked ranking ceiling','', 'Frozen retrieval ceiling 15/16; ranked Top-3 ceiling 14/16, maximum theoretical success 14/16. Stored ranked handles are reused exactly. No retrieval, embedding, ranking or selector A/B/C rerun; no denominator exclusion.','',
 '## M. Locked strict target conversion','', `${m.strictTargetConversion}/16 = ${pct(m.strictTargetConversionRate)}; pre-registered floor ${g.capability.minimumStrictTargetConversions}/16. Every success requires legal source/parse/Validator/Candidate, intent gates, expected Gold support and the unchanged strict numeric/unit/period/category scorer. Gold is evaluator-only and never drives fallback.`, '',
 '## N. Conditional target conversion among Top-3 reachable cases','', `${m.strictGivenTop3.numerator}/14 = ${pct(m.strictGivenTop3.rate)}; pre-registered floor 10/14. Fixed denominator 14.`, '',
 '## O. Valid-but-wrong-target Candidate count','',`${m.validButWrongTargetCandidates}, compared with historical 6. Pre-registered maximum 0. A valid-but-wrong-target Candidate is never target success and also fails the real-run false-accept hard gate.`, '',
 '## P. Generic Candidate conversion (secondary)','',`${m.genericCandidateConversion}/16. Strict target conversions by fallback depth: rank 1 ${m.rankConversion[1]}/16; rank≤2 ${m.rankConversion[2]}/16; rank≤3 ${m.rankConversion[3]}/16. candidateFoundAtRank is 1/2/3/null. Each accepted Candidate has a persisted sidecar binding intentId/version/hash, targetMatch, sourceSupportId/hash and rankUsed.`, '',
 '## Q. Failure taxonomy','',JSON.stringify(r.failures), '',
 '## R. Latency','',`Frozen historical ranking median ${sec(r.latency.ranking.median)}, new ranking calls 0. Target-match plus interpretation median ${sec(r.latency.targetMatchAndInterpretation.median)}, p95 ${sec(r.latency.targetMatchAndInterpretation.p95)}. These operations share one model call; separate latency is unavailable and is not invented or added twice. Parser/Validator median ${sec(r.latency.parserValidator.median)}. Conversion end-to-end median ${sec(r.latency.endToEnd.median)}, p95 ${sec(r.latency.endToEnd.p95)}, excluding frozen offline retrieval/ranking.`, '',
 '## S. Safety','',JSON.stringify(r.safety)+'. No parser, unit, period or Validator weakening. Source identity is exact; no fuzzy handle repair. Intent mismatch/ambiguity prevents Candidate creation. Real source semantics are still a constrained model proposal, not a deterministic proof of arbitrary finance. Synthetic injection boundary is tested offline; no separate real injection or cloud benchmark was run.', '',
 '## T. Claims protection','',`Claims ${r.claimsProtection.before.claims}→${r.claimsProtection.after.claims}; revisions ${r.claimsProtection.before.revisions}→${r.claimsProtection.after.revisions}; unchanged=${r.claimsProtection.unchanged}. Payload hash ${r.claimsProtection.after.payloadHash}. No Evidence or Admission writes and no Claim Revision.`, '',
 '## U. Paid API proof','',`paidInferenceApiCostUsd=0; paidEmbeddingApiCostUsd=0; paid inference/embedding API calls=0. Locked local calls ${r.tokens.calls}, input ${r.tokens.input}, output ${r.tokens.output}, total ${r.tokens.total}. Existing loopback-only Ollama provider with remote guard; cloud disabled.`, '',
 '## V. Resource usage','',JSON.stringify(r.resource)+'. Ollama was off during offline diagnosis, dev and all pre-run gates; started only after registration '+g.registeredAt+'. One conversion-only locked run, no real development smoke, no embedding/ranking calls, no larger/cloud models, no fine-tuning. Completed cases resume with gate/code/history/schema/provider drift checks. caffeinate covers the real run. Ollama was stopped after completion; loopback port 11434 has no listener.',resource?`Observed sampled Ollama/runner RSS peak ${(Math.max(...resource.samples.map(s=>s.ollamaAndRunnerRssBytes))/1073741824).toFixed(2)} GiB on ${resource.cpu}, ${(resource.totalMemoryBytes/1073741824).toFixed(0)} GiB RAM. Sampling begins at ${resource.samples[0].at}; it does not include the earliest cold-load peak.`:'RSS sample unavailable.', '',
 '## W. Regression','', 'Before real inference: 123 agent tests and 6 target-conversion tests (21 dev scenarios), syntax, frontend discipline, isolation and full verify-release PASS. After the locked run: 124 agent tests and 7 target-conversion tests PASS, including locked artifact/gate/code/history/sidecar consistency. Syntax (191 JS files), frontend discipline, development isolation and complete verify-release PASS. CSS and all frontend/frozen code remain unchanged.', '',
 '## X. Decision','', '**'+r.decision+'**. '+(r.passed?'The strict primary capability, zero wrong-target and all safety hard gates pass. A later stage may consider Claim Revision Proposal; this delivery does not start it.':'The pre-registered gate does not pass; remain on target conversion. Do not change the frozen thresholds or re-run locked exploration, and do not enter Claim Revision.'), '',
 '## Locked per-case result','', '|Case|Top-3 target rank|Candidate rank|Strict target|Failure|Model calls|','|---|---:|---:|---:|---|---:|',...r.rows.map(x=>{const old=JSON.parse(readFileSync(resolve(root,'research/eval/selector-ranking/results.json'),'utf8')).rows.find(o=>o.caseId===x.caseId),rank=old.selectedSpanIds.findIndex(id=>old.expectedSpanIds.includes(id))+1;return `|${x.caseId}|${rank||'miss'}|${x.candidateFoundAtRank??'null'}|${x.targetCorrect?'yes':'no'}|${x.failure}|${x.receipts.length}|`;})];
writeFileSync(resolve(root,'research/target-conversion/DELIVERY.md'),lines.join('\n')+'\n');
writeFileSync(resolve(root,'docs/target-bound-evidence-conversion-v0.11.3.md'),lines.join('\n')+'\n');
writeFileSync(resolve(art,'runtime-costs.json'),JSON.stringify({version:'target-conversion-runtime-costs/v0.11.3',provider:r.provider,tokens:r.tokens,latency:r.latency,resource:{...r.resource,samples:resource},paidInferenceApiCostUsd:0,paidEmbeddingApiCostUsd:0,paidInferenceApiCalls:0,paidEmbeddingApiCalls:0},null,2)+'\n');
console.log(r.decision);
