import {stats} from '../local-retrieval/eval.js';
import {classifyCase,failureDecomposition,invalidHandleReport,evaluateHandleGate,comparisonAgainstBaseline,handleGateDecisions} from './eval.js';
import {selectionHandleVersion,selectionHandlesPromptVersion} from './handles.js';

// Assembly of the v0.11.1 artifacts. Like the v0.11 assembler it is a pure
// function of a finished arm plus the registered gate, so a mistake here is
// caught by an offline test instead of by another locked run.
export function assembleHandleRun({arm,gate,context,embedding,chat,spanIndex,findings,resource,warm,hardware,sessionUsage}){
 const caseRecords=arm.caseRecords,metrics=arm.result.metrics,retrievalMetricsReport=arm.measurement.retrievalMetrics;
 const rows=arm.result.scores.map((score,index)=>{
  const record=caseRecords.get(score.caseId)??null;
  const expected=context.annotation.cases.find(entry=>entry.caseId===score.caseId).expectedSpanIds;
  const decomposition=classifyCase({caseRecord:record,score,expectedSpanIds:expected,retrievalReceipt:record?.retrieval??null});
  const handleOf=new Map((record?.selectionInterface?.handles??[]).map(entry=>[entry.spanId,entry.handle]));
  return {caseId:score.caseId,expectedSupportType:score.expectedSupportType,targetSelected:score.targetSelected,numericCorrect:score.numericCorrect,unitCorrect:score.unitCorrect,periodCorrect:score.periodCorrect,categoryCorrect:score.categoryCorrect,chainParseOnly:score.chainParseOnly,chainCorrect:score.chainCorrect,proposalValidated:score.proposalValidated,converted:score.converted,validatorFalseReject:score.validatorFalseReject,selectedCount:score.selectedCount,nonTargetSelections:score.nonTargetSelections,findings:score.findings,failure:decomposition.failure,detail:decomposition.detail,status:record?.status??null,candidateCount:record?.candidateCount??null,retrievedCount:record?.retrievedCount??null,selectedHandles:(record?.selectedSpanIds??[]).map(spanId=>handleOf.get(spanId)??null),selectedSpanIds:record?.selectedSpanIds??[],invalidHandles:record?.invalidHandles??[],inputTokens:arm.payload.extra.tokenStats.perCase[index]??null,endToEndLatencyMs:arm.result.results?.[index]?.endToEndLatencyMs??null};
 });
 const decomposition=failureDecomposition({caseRows:rows}),invalidHandles=invalidHandleReport({caseRecords});
 const safety={invalidSelectionHandles:invalidHandles.references,fabricatedSupport:metrics.fabricatedSupportRate.numerator,sourceSupportFidelity:metrics.sourceSupportFidelity.rate,falseAccept:metrics.validatorFalseAccepts,futureLeakage:arm.futureLeakage.count,wrongSubject:arm.responses.reduce((total,response)=>total+(response.filtered?.wrongSubject??0),0),claimMutation:arm.result.claimsProtection.unchanged===true?0:1};
 const capability={targetSelectionRate:metrics.targetSelectionRate.rate,candidateConversionRate:metrics.candidateConversionRate.rate};
 const efficiency={timeouts:arm.caseRows.filter(row=>row.failure==='PROVIDER_TIMEOUT').length};
 const recall=retrievalMetricsReport.recallAtK['recallAt'+gate.retrieval.k];
 const gateResult=evaluateHandleGate({gate,safety,capability,efficiency,retrieval:{recallAtK:recall.rate}});
 const decision=gateResult.passed?handleGateDecisions.ready:handleGateDecisions.stay;
 const endToEnd=stats(arm.result.results.map(result=>result.endToEndLatencyMs));
 const resultsPayload={version:'selection-handles-results/v0.11.1',generatedAt:new Date().toISOString(),decision,status:decision,gate:gateResult,provider:chat.metadata,embedding:{model:embedding.metadata.model,modelDigest:embedding.metadata.modelVersion,dimension:embedding.metadata.dimension,indexRecords:spanIndex.count()},selection:{interface:'handles',handleVersion:selectionHandleVersion,promptVersion:selectionHandlesPromptVersion,invalid:invalidHandles,canonicalIdsExposedToModel:false},retrieval:{mode:gate.fusionMode,limit:gate.retrieval.limit,frozenK:gate.frozenK,recallAtK:recall},metrics,capability,safety,efficiency,decomposition,latency:{selection:arm.payload.extra.phaseLatencyMs?.selection??null,interpretation:arm.payload.extra.phaseLatencyMs?.interpretation??null,endToEnd:{count:endToEnd.count,medianMs:endToEnd.median,p95Ms:endToEnd.p95,exploratory:true}},claimsProtection:arm.result.claimsProtection,futureLeakage:arm.futureLeakage,injection:{summary:arm.payload.extra.injection?.summary??null,usage:arm.injectionUsage},forbiddenFindings:findings,cases:rows};
 const comparison={version:'selection-handles-comparison/v0.11.1',generatedAt:new Date().toISOString(),subject:'locked 16 CoreWeave Gold; v0.11 hybrid retrieval (K=8) and the frozen Qwen model, with the model-facing selection interface as the only experimental variable: canonical span ids in v0.11 against invocation-local handles in v0.11.1',baseline:gate.baseline,table:comparisonAgainstBaseline({baseline:{targetSelectionRate:gate.baseline.targetSelectionRate,candidateConversionRate:gate.baseline.candidateConversionRate,timeouts:gate.baseline.timeouts,invalidSelectionHandles:null,fabricatedSupport:gate.baseline.fabricatedSupport,chainCorrectRate:gate.baseline.chainCorrectRate},current:{targetSelectionRate:capability.targetSelectionRate,candidateConversionRate:capability.candidateConversionRate,timeouts:efficiency.timeouts,invalidSelectionHandles:invalidHandles.references,fabricatedSupport:safety.fabricatedSupport,chainCorrectRate:metrics.chainCorrectRate.rate}}),retrieval:{mode:gate.fusionMode,limit:gate.retrieval.limit,recallAtK:recall,retrievalMetrics:retrievalMetricsReport},decomposition:{counts:decomposition.counts,succeeded:decomposition.succeeded,examples:decomposition.examples},resolvedHandles:rows.map(row=>({caseId:row.caseId,selectedHandles:row.selectedHandles,selectedSpanIds:row.selectedSpanIds,invalidHandles:row.invalidHandles}))};
 const runtimeCosts={version:'selection-handles-runtime-costs/v0.11.1',generatedAt:new Date().toISOString(),provider:{provider:chat.metadata.provider,model:chat.metadata.model,modelDigest:chat.metadata.modelVersion,runtime:chat.metadata.runtime},embedding:{provider:embedding.metadata.provider,model:embedding.metadata.model,modelDigest:embedding.metadata.modelVersion,runtime:embedding.metadata.runtime,dimension:embedding.metadata.dimension},paidInferenceApiCostUsd:0,paidInferenceApiCalls:0,paidEmbeddingApiCostUsd:0,paidEmbeddingApiCalls:0,coldStartMs:warm.coldStartMs,modelLoadMs:warm.loadMs,gold:{v0111:arm.tokens},injection:{v0111:arm.injectionUsage},total:{session:sessionUsage},phases:{v0111:arm.payload.extra.phaseLatencyMs},resource,note:'Paid inference API cost is zero and paid embedding API cost is zero because no paid inference or embedding API was called. Hardware, electricity, disk and elapsed wall time are not zero and are reported separately.'};
 const hardwareArtifact={...hardware,provider:chat.metadata,embedding:embedding.metadata,endpoint:chat.describe().endpoint,embeddingEndpoint:embedding.describe().endpoint,coldStartMs:warm.coldStartMs,modelLoadMs:warm.loadMs,resource};
 return {resultsPayload,comparison,runtimeCosts,hardware:hardwareArtifact,decision,gateResult,efficiency,safety,capability,decomposition,invalidHandles,retrievalMetricsReport};
}
