import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {RetrievalIndex,defaultIndex} from '../retrieval/index.js';
import {ProposalStore} from '../analyst/store.js';
import {claimsReader,externalDirectory} from '../analyst-real/cli.js';
import {configuredProvider} from '../analyst-real/provider.js';
import {normalizeSource} from '../src/normalize-source.js';
import {parseDocument,byteHash} from '../retrieval/parser.js';
import {StagedStore} from './store.js';
import {runEvaluation,sanitized} from './eval.js';
const repository=fileURLToPath(new URL('../../',import.meta.url));
export const development=JSON.parse(readFileSync(new URL('./development.json',import.meta.url)));
export function buildDevelopment(index,folder,{clock=()=>new Date().toISOString()}={}){return development.map(c=>{const html='<p>'+c.text+'</p>',filename=resolve(folder,c.caseId+'.html'),at=clock();writeFileSync(filename,html,{mode:0o600});const source=normalizeSource({subjectId:'synthetic',sourceType:'official_announcement',title:'Staged development '+c.caseId,publisher:'Synthetic Publisher',url:'https://example.invalid/'+c.caseId,documentDate:'2026-01-01',retrievedAt:at,fiscalPeriod:'FY2025',fiscalYear:2025,isPrimarySource:true,contentHash:byteHash(Buffer.from(html)),metadata:{documentKey:c.caseId,hashStatus:'verified_bytes',hashScope:'document_bytes',retrievalNote:'Separate v0.7 development fixture',discoveryUrl:'https://example.invalid/'}});index.indexDocument(parseDocument({source,filename,format:'html',availability:{availableAt:'2026-01-01T00:00:00.000Z',basis:'Synthetic development availability; not real financial disclosure',scope:'entire_document',firstPage:1},retrievedAt:at,createdAt:at}));return {...c,kind:'development',subjectId:'synthetic',chunkId:index.list('chunk').find(x=>x.sourceId===source.id).id};});}
export async function runCli(args){const [command,target,...rest]=args;if(!['staged-dev','staged-eval'].includes(command)||target!=='coreweave')throw Error('Usage: cli.js staged-dev|staged-eval coreweave --real true [--provider deepseek]');const options={};for(let n=0;n<rest.length;n+=2){const k=rest[n]?.slice(2);if(!rest[n]?.startsWith('--')||!['real','provider','results','index','memory'].includes(k)||options[k]!==undefined||!rest[n+1]||rest[n+1].startsWith('--'))throw Error('Invalid explicit option');options[k]=rest[n+1];}if(options.real!=='true')throw Error('Explicit --real true required');const provider=configuredProvider({provider:options.provider??'deepseek'});if(!provider)return {status:'REAL_MODEL_BENCHMARK_BLOCKED'};if(provider.metadata.provider!=='deepseek'||provider.metadata.model!=='deepseek-v4-flash')throw Error('Primary comparison requires same DeepSeek model as v0.6');const root=externalDirectory(options.results??resolve(repository,'..','fc-agent','research-analyst-staged')),folder=externalDirectory(resolve(root,'session-'+Date.now())),index=new RetrievalIndex(command==='staged-dev'?resolve(folder,'dev-index.sqlite'):options.index??defaultIndex);let proposals,store,memory;
 try{proposals=new ProposalStore(resolve(folder,'proposals.sqlite'));store=new StagedStore(folder);memory=claimsReader(options.memory??resolve(repository,'..','fc-agent','research-memory','v0.2-coreweave.sqlite'));const cases=command==='staged-dev'?buildDevelopment(index,folder):null,result=await runEvaluation({index,proposals,store,provider,cases,readClaimsSnapshot:memory.read});result.experiment=command;result.runtimeFolder=folder;writeFileSync(resolve(root,result.runId+'.raw.json'),JSON.stringify(result,null,2),{mode:0o600});const safe=sanitized(result);writeFileSync(resolve(root,result.runId+'.json'),JSON.stringify(safe,null,2),{mode:0o600});return safe;}finally{memory?.close();store?.close();proposals?.close();index.close();}
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{console.log(JSON.stringify(await runCli(process.argv.slice(2)),null,2));}catch(e){console.error(e.message);process.exitCode=1;}}
