import {digest,stableId} from '../src/identity.js';
import {instant} from '../memory/time.js';
import {cutoffVisible} from '../retrieval/layer.js';
import {freshChunk,validateProposal,validatorHash,validationVersion} from '../analyst/validation.js';
import {assertProposal,outputSchema,validateProvider} from '../analyst/contract.js';
import {EvidenceAnalyst} from '../analyst/layer.js';
import {spanInstructions,spanSchema,spanPromptVersion,spanPromptHash,interpretationInstructions,interpretationSchema,interpretationPromptVersion,interpretationPromptHash,parseStructured,assertContract} from './contract.js';
import {parseNumeric,parsePeriod} from './parsers.js';
function freeze(value){if(value&&typeof value==='object'){Object.freeze(value);Object.values(value).forEach(freeze);}return value;}
export function validateSpan(item,chunk){const findings=[];if(!chunk.text.includes(item.quote))findings.push('QUOTE_HALLUCINATION');if(item.quote.length>1000||chunk.text.length>400&&item.quote.length>chunk.text.length*.8)findings.push('QUOTE_TOO_BROAD');if(/ignore (?:previous|prior) instructions|return accepted|mark .*low risk|reveal .*prompt/i.test(item.quote))findings.push('INSTRUCTION_LIKE_CONTENT');return {validationStatus:findings.length?'rejected':'verified',findings};}
export function parseFact(fact,span){
 const quote=span.quote,findings=[];for(const [key,code] of [['rawValueText','VALUE_ERROR'],['rawUnitText','UNIT_ERROR'],['periodText','PERIOD_ERROR']])if(fact[key]!==null&&!quote.includes(fact[key]))findings.push(code);
 if(fact.explicitOrDerived!=='explicit')findings.push('DETERMINISTIC_PARSE_UNSUPPORTED');
 if(/risk_grade|risk_score|accepted|thesis|target_price|\bbuy\b|\bsell\b/i.test(fact.metric))findings.push('FORBIDDEN_JUDGMENT');
 if(/\bexpect(?:s|ed)?\b|anticipate|guidance|forecast|project/i.test(quote)&&fact.actualOrGuidance!=='guidance')findings.push('ACTUAL_GUIDANCE_ERROR');
 if(fact.actualOrGuidance==='guidance'&&fact.metricOrCategory!=='guidance')findings.push('ACTUAL_GUIDANCE_ERROR');
 const numeric=parseNumeric(fact.rawValueText,fact.rawUnitText,{quote}),period=quote.includes(fact.periodText??'')?parsePeriod(fact.periodText):{status:'unknown'};
 if(numeric.status!=='known'||period.status!=='known')findings.push('DETERMINISTIC_PARSE_UNSUPPORTED');
 if(fact.actualOrGuidance==='risk_disclosure'&&numeric.status==='known')findings.push('ACTUAL_GUIDANCE_ERROR');
 return {numeric,period,findings:[...new Set(findings)],status:findings.length?'unsupported':'parsed'};
}
export class StagedAnalyst{
 #index;#proposals;#store;#provider;#metadata;#clock;#timeout;
 constructor(index,proposals,store,{provider=null,clock=()=>new Date().toISOString(),timeoutMs=60000}={}){if(!Number.isInteger(timeoutMs)||timeoutMs<1||timeoutMs>60000)throw Error('Bounded timeout required');this.#index=index;this.#proposals=proposals;this.#store=store;this.#provider=provider?validateProvider(provider):null;this.#metadata=provider?structuredClone(provider.metadata):null;this.#clock=clock;this.#timeout=timeoutMs;}
 #context(id,options){if(Object.keys(options).some(k=>!['subjectId','asOf','timeMode'].includes(k))||!options.subjectId)throw Error('Explicit context only; no Claim state');const context={subjectId:options.subjectId,asOf:instant(options.asOf,{query:true}),timeMode:options.timeMode??'replay'};if(!['replay','audit'].includes(context.timeMode))throw Error('Unknown time mode');const chunk=this.#index.get('chunk',id),doc=chunk?this.#index.get('document',chunk.documentId):null,at=instant(this.#clock());if(!chunk||!doc||chunk.subjectId!==context.subjectId||doc.source.subjectId!==context.subjectId||doc.subjectId!==context.subjectId||chunk.sourceId!==doc.source.id||instant(doc.createdAt)>at||instant(doc.retrievedAt)>at)throw Error('SOURCE_IDENTITY_INVALID');if(!cutoffVisible(chunk,context.asOf,context.timeMode)||!cutoffVisible(doc,context.asOf,context.timeMode))throw Error('TEMPORAL_INVALID');if(freshChunk(this.#index,id,context).validation.validationStatus!=='valid')throw Error('CITATION_INVALID');return {context,chunk,doc,at};}
 async #call(input,name){const frozen=freeze(input),inputHash=digest(frozen),start=performance.now(),receiptStart=this.#provider.receipts?.length??0,controller=new AbortController();let timer,raw=null,error=null,parsed=null;
 try{raw=await Promise.race([this.#provider.analyzeEvidence(frozen,{signal:controller.signal}),new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(Error('PROVIDER_TIMEOUT'));},this.#timeout);})]);if(digest(frozen)!==inputHash||digest(this.#provider.metadata)!==digest(this.#metadata))throw Error('INPUT_OR_PROVIDER_MUTATION');parsed=parseStructured(raw,name);}catch(e){error=/^(?:PROVIDER_[A-Z_]+|INPUT_OR_PROVIDER_MUTATION|CONTRACT_SCHEMA_INVALID)$/.test(e.message)?e.message:'PROVIDER_ERROR';}finally{clearTimeout(timer);}
 const run=this.#store.save('run',{id:stableId('STAGED-RUN',{inputHash,rawHash:typeof raw==='string'?digest(raw):null,at:this.#clock()}),inputHash,outputHash:typeof raw==='string'?digest(raw):null,rawResponse:typeof raw==='string'&&Buffer.byteLength(raw)<=100000?raw:null,rawDiscarded:typeof raw==='string'&&Buffer.byteLength(raw)>100000,inputSnapshot:frozen,promptVersion:input.promptVersion,promptHash:input.promptHash,createdAt:this.#clock(),schemaValid:parsed!==null,wrapperRemoved:parsed?.wrapperRemoved??false,error,latencyMs:performance.now()-start,receipts:this.#provider.receipts?.slice(receiptStart)??[]});return {parsed,run};
 }
 async analyzeChunk(id,options){if(!this.#provider)return {status:'REAL_MODEL_BENCHMARK_BLOCKED',spans:[],facts:[],proposals:[]};const first=this.#context(id,options),source={id:first.doc.source.id,subjectId:first.doc.source.subjectId,documentDate:first.doc.source.documentDate,title:first.doc.source.title,isPrimarySource:first.doc.source.isPrimarySource};
 const p1=await this.#call({instructions:spanInstructions,outputSchema:spanSchema,promptVersion:spanPromptVersion,promptHash:spanPromptHash,data:{subjectId:options.subjectId,asOf:first.context.asOf,timeMode:first.context.timeMode,chunk:{id:first.chunk.id,source,text:first.chunk.text,contentHash:first.chunk.contentHash,documentHash:first.doc.contentHash,locator:first.chunk.locator,availableAt:first.chunk.availableAt}}},'span-output');
 const spans=[],facts=[],proposals=[],interpretationRuns=[],parsing=[];if(!p1.parsed)return {status:'SPAN_SCHEMA_ERROR',spanRun:p1.run,spans,facts,proposals,interpretationRuns,parsing};
 for(const item of p1.parsed.value){const span=assertContract('span-proposal',{id:stableId('SPAN',{inputHash:p1.run.inputHash,outputHash:p1.run.outputHash,createdAt:p1.run.createdAt,item}),...item,subjectId:options.subjectId,sourceId:source.id,chunkId:id,quoteHash:digest(item.quote),modelProvider:this.#metadata.provider,modelName:this.#metadata.model,modelVersion:this.#metadata.modelVersion,promptVersion:spanPromptVersion,promptHash:spanPromptHash,inputHash:p1.run.inputHash,outputHash:p1.run.outputHash,createdAt:this.#clock(),inputSnapshot:p1.run.inputSnapshot,...validateSpan(item,first.chunk)});this.#store.save('span',span);spans.push(span);if(span.validationStatus!=='verified')continue;
 const current=this.#context(id,options);if(current.chunk.contentHash!==first.chunk.contentHash||current.doc.contentHash!==first.doc.contentHash||digest(current.chunk.locator)!==digest(first.chunk.locator)||!current.chunk.text.includes(span.quote))throw Error('SOURCE_CHANGED');
 const p2=await this.#call({instructions:interpretationInstructions,outputSchema:interpretationSchema,promptVersion:interpretationPromptVersion,promptHash:interpretationPromptHash,data:{spanProposalId:span.id,verifiedQuote:span.quote,quoteHash:span.quoteHash,factKind:span.factKind,source}},'interpretation-output');interpretationRuns.push(p2.run);if(!p2.parsed)continue;
 const fact=assertContract('interpreted-fact',{...p2.parsed.value,id:stableId('INTERPRETED',{spanProposalId:span.id,inputHash:p2.run.inputHash,outputHash:p2.run.outputHash}),spanProposalId:span.id,inputHash:p2.run.inputHash,outputHash:p2.run.outputHash,promptVersion:interpretationPromptVersion,promptHash:interpretationPromptHash,createdAt:this.#clock()});this.#store.save('fact',fact);facts.push(fact);const parsed=parseFact(fact,span);this.#store.save('parse',{id:stableId('PARSED',{factId:fact.id,parsed}),factId:fact.id,spanProposalId:span.id,...parsed});parsing.push({factId:fact.id,spanProposalId:span.id,...parsed});if(parsed.status!=='parsed')continue;
 const last=this.#context(id,options);if(last.chunk.contentHash!==first.chunk.contentHash||last.doc.contentHash!==first.doc.contentHash)throw Error('SOURCE_CHANGED');
 const n=parsed.numeric,p=parsed.period,generatedAt=instant(this.#clock()),input={instructions:spanInstructions+'\n'+interpretationInstructions,outputSchema,promptVersion:'evidence-contract/v2',promptHash:digest(spanInstructions+'\n'+interpretationInstructions),data:{...last.context,generatedAt,mode:'direct_chunk',query:null,chunks:[{id,documentId:last.doc.id,source,text:last.chunk.text,contentHash:last.chunk.contentHash,documentHash:last.doc.contentHash,locator:last.chunk.locator,availableAt:last.chunk.availableAt}]}},inputHash=digest(input);
 const finalItem={subjectId:options.subjectId,sourceIds:[source.id],chunkIds:[id],statement:span.quote,quotedText:span.quote,researchField:fact.metricOrCategory,category:fact.metricOrCategory,metric:fact.metric,scope:'consolidated_company',factType:'explicit',rawValue:n.numericValue,proposedNormalizedValue:n.normalizedValue,rawUnit:n.rawUnit,unit:n.unit,normalization:n.normalization,observedAt:p.observedAt,periodStart:p.start,periodEnd:p.end,periodStatus:'known',periodBasis:'quote'};
 const provenance={validationVersion,validatorHash,modelProvider:this.#metadata.provider,modelName:this.#metadata.model,modelVersion:this.#metadata.modelVersion,providerKind:this.#metadata.kind,temperature:this.#metadata.temperature,promptVersion:input.promptVersion,promptHash:input.promptHash},outputHash=digest(finalItem),proposal=assertProposal({id:stableId('PROP-STAGED',{item:finalItem,inputHash,outputHash,...provenance}),...finalItem,...provenance,inputHash,outputHash,rawResponseHash:p2.run.outputHash,createdAt:generatedAt,inputSnapshot:input,...validateProposal(this.#index,finalItem,input)});
 this.#proposals.saveRun({id:stableId('STAGED-FINAL',{proposalId:proposal.id}),inputHash,outputHash,inputSnapshot:input,spanProposalId:span.id,factId:fact.id,proposalIds:[proposal.id],createdAt:generatedAt},[proposal]);proposals.push(proposal);
 }
 return {status:p1.parsed.value.length?'generated':'abstained',spanRun:p1.run,spans,facts,proposals,interpretationRuns,parsing};
 }
 promote(id){return new EvidenceAnalyst(this.#index,this.#proposals,{clock:this.#clock}).promoteProposalToCandidate(id);}
}
