import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),art=resolve(root,'research/eval/claim-revision');
const read=n=>JSON.parse(readFileSync(resolve(art,n+'.json'),'utf8'));
const r=read('results'),g=read('phase-gate'),d=read('development');
const pct=n=>(100*n).toFixed(2)+'%',latencies=r.rows.map(r=>r.latencyMs).sort((a,b)=>a-b),median=(latencies[(latencies.length-1)>>1]+latencies[latencies.length>>1])/2;
const samplePath=resolve(root,'../fc-agent/research-claim-revision/resource-samples.json'),samples=existsSync(samplePath)?JSON.parse(readFileSync(samplePath)):null;
const first=r.rows.find(row=>row.proposal&&row.score.impactCorrect&&row.score.attributionCorrect)??r.rows.find(row=>row.proposal);
const rawImpactCorrect=r.rows.filter(row=>row.output?.impact===row.expectedImpact).length;
const invalidQuotes=r.rows.filter(row=>(row.output?.attributions??[]).some(a=>!row.modelInput.evidence.find(e=>e.handle===a.evidenceHandle)?.statement.includes(a.quote))).length;
const oldRoleErrors=r.rows.filter(row=>(row.output?.attributions??[]).some(a=>{const e=row.modelInput.evidence.find(e=>e.handle===a.evidenceHandle);return e&&!e.isNew&&a.relation!==(e.contextOnly?'context':'supports');})).length;
const sections=[
 ['A. Push confirmation for bb66cc1','The clean complete v0.11.3 baseline bb66cc1d48524e440ffc678a3d77e75df1802bf6 was pushed to origin/main and independently verified. Production push is disabled; baseline history remains unchanged.'],
 ['B. Claim authority audit','ResearchMemory.createClaim/reviseClaim → private #writeRevision → append-only Memory transaction is authoritative. Identity = id/subjectId/createdAt; revision = full belief snapshot plus version/predecessor/reason/note/effective and recording times. Diff/status order is a comparison rule, not impact. Correction preserves history, and old superseded references can persist until explicit human revision. Proposal code has only read capabilities and separate persistence. Full audit: research/claim-revision/REPOSITORY_AUDIT.md.'],
 ['C. Files changed','All files are additive:\n\n- research/claim-revision/REPOSITORY_AUDIT.md: authority, identity, provenance, temporal/confidence audit.\n- contract.js and two *.schema.json: independent proposal and strict model output contracts.\n- reader.js: read-only Memory/Admission snapshots and bounded revision summaries.\n- context.js: Accepted Evidence/subject/time/base/category checks and exact aliases.\n- validation.js: exact quote/reference/impact-status checks and deterministic summary/hashes.\n- layer.js: one bounded reasoning call → validated Proposal only.\n- store.js: independent external immutable Proposal/review SQLite; no apply writer.\n- fixtures.js/dev.js: independently constructed synthetic admissions/Claims and offline matrix.\n- eval.js/cli.js: fixed evaluation, preregistration, guarded one-run receipts/resume/protection.\n- report.js/README.md: delivery and usage/lifecycle/limitations.\n- research/prompts/claim-impact-v012.txt: one frozen impact prompt.\n- research/claim-revision-test/*.test.js and agent/test/claim-revision-proposal.test.js: offline safety, lifecycle, reasoning and artifact checks integrated into CI.\n- research/eval/claim-revision/*.json: dev/freeze/gate/held-out/results/cost/resource/push/protection/pending proof, including failed registration trace.\n- docs/claim-revision-proposal-v0.12.md and research/claim-revision/DELIVERY.md: A–X measured report.\n\nFrozen frontend, Memory authority, acquisition stack, public API versions and every v0.1–v0.11.3 benchmark artifact: zero modifications.'],
 ['D. ClaimRevisionProposal schema','claim-revision-proposal/v0.12: proposalId/subjectId/claimId/baseRevisionId/hash; resolved Accepted Evidence IDs; impact/suggestedStatus/confidence direction; finite reasonCode and exact-source reasonSummary/attributions; provider/name/config/prompt/hash; inputHash/outputHash; Audit asOf/public availability/knowledge/base effective/proposal-created times; exact handle map and full bounded input/output provenance; lifecycle pending. additionalProperties=false at output/proposal/attribution boundaries. Independent Candidate, Evidence, Claim and Revision schemas remain unchanged.'],
 ['E. Impact taxonomy','confirm, strengthen, weaken, contradict, no_material_effect, insufficient_evidence. Impact describes evidence effect; suggestedStatus is independently restricted to existing supported/partially_supported/disputed/unverified/stale. No numeric confidence update; increase/decrease/unchanged only.'],
 ['F. Reason taxonomy','new_supporting_evidence, new_counter_evidence, conflicting_evidence, period_update, metric_deterioration, metric_improvement, source_correction, insufficient_support, no_relevant_change. These are proposal reasons, not automatic authoritative revision commands.'],
 ['G. Evidence handle architecture','Provider sees C1/R1/E1…E8, never canonical Claim/Revision/Evidence/Source IDs. IDs resolve exactly with no whitespace/case/fuzzy repair. Require actual accepted Admission reviews; historical reviewed imports without Admission do not qualify. system_test fixture/recovery acceptance is labeled test capability, not authenticated human approval. Superseded history is context only. Provenance preserves Proposal → base revision → Accepted Evidence → Admission snapshot Candidate/support metadata (when present) → Chunk/Source. Legacy v0.4 may have Chunk rather than a newer SourceSpan; the system does not fabricate a missing SourceSpan.'],
 ['H. Temporal model','Audit only: ingestion, Evidence extraction, Source retrieval, Admission accepted/recorded and known public availability ≤ asOf; base recording/effective time ≤ asOf ≤ proposalCreatedAt. Date-only cutoffs use UTC end-of-day. observedAt is not availability. Maximum four new items, two existing support/two counter, three revision summaries. Replay theoretically public knowledge is distinct and explicitly rejected here, never backdated into Audit. New superseded Evidence rejects; historical replaced facts cannot be authoritative attribution.'],
 ['I. Deterministic validation','Claim exists; exact visible base; accepted Evidence exists; subject/category/time/source hash match; no new superseded item; output schema/enum; exact handles/contiguous quotes; new Evidence attribution; impact/status/reason/direction compatibility; no forbidden investment language; full snapshot/hash/ID recomputation. Exact quotes establish source fidelity, not arbitrary semantic entailment. A valid proposal remains a suggestion for human review.\n\n'+JSON.stringify(r.safety)],
 ['J. Proposal persistence','Separate external SQLite storage version 12, immutable Proposal/review tables, transactions and hash verification; repository/symlink paths and Memory database reuse reject. Same ordered bounded input/base/evidence/prompt/model config yields stable input key and Proposal ID; input order determines aliases and is part of the context hash; repeated input returns existing Proposal without new inference. Different output for the same input conflicts instead of overwriting. Model response/receipts checkpoint before Proposal persistence; completed-case resume, drift checks, in-flight/failed call blocks automatic retry.'],
 ['K. Human review lifecycle','pending → accepted/rejected; stale derives from current base/hash or correction changes. Exact Proposal hash and latest previousReviewId required. Human local identity is explicit but self-asserted. system_test review requires explicit test constructor; agent/LLM cannot review. Rejection retains original Proposal/review/reason. Accepted review never calls reviseClaim; there is no apply operation. Stale proposals cannot be accepted but may be rejected. No authenticated multi-user security claim.'],
 ['L. Development fixtures',`${d.cases} independent offline scenarios: confirm/strengthen/weaken/contradict/no effect/insufficient/conflicting/latest-period/correction; all PASS. Scripted responses exercise real frozen parser/Validator/Admission/Memory setup and Proposal validation/store/review, not model accuracy. Zero real dev/smoke inference. Adversarial tests cover handles, unsupported quotes, investing, acceptance, temporal/source/subject/base/category, idempotence, hashes, actor boundaries, stale review and immutable SQL.`],
 ['M. Locked benchmark',`${r.metrics.cases} synthetic cases, six balanced impacts, independent wording/values; held-out set constructed after prompt/schema freeze, never supplied as answers to the model. Exactly one impact-only local benchmark. Frozen qwen3.5:9b/Q4_K_M/non-thinking/temp0/context8192; one bounded call per case. No acquisition, ranking, embedding, cloud or model switch. All denominators fixed; validation rejects count as failed capability, even with correct raw impact.`],
 ['N. Impact accuracy',`${pct(r.metrics.impactAccuracy)} overall; weaken/contradict ${pct(r.metrics.weakenContradictAccuracy)}. Pre-registered minima 75% and 75%. Raw impact enum matches (secondary, without validation) ${rawImpactCorrect}/${r.metrics.cases}; this does not replace the strict primary score.\n\n|Impact|Correct|Total|Accuracy|\n|---|---:|---:|---:|\n`+Object.entries(r.metrics.byImpact).map(([k,v])=>`|${k}|${v.correct}|${v.total}|${pct(v.accuracy)}|`).join('\n')],
 ['O. Evidence attribution accuracy',`${pct(r.metrics.evidenceAttributionAccuracy)}; minimum 90%. Evaluator requires all adjudicated new evidence handles with correct supports/counters/context/unclear relationships and exact quotations, no fabricated references; old references are checked against retained support/counter/context roles. Schema validity ${pct(r.metrics.schemaValidity)}; validated Proposal rate ${pct(r.metrics.validatedProposalRate)}; insufficient-evidence abstention accuracy ${pct(r.metrics.abstentionAccuracy)}.`],
 ['P. Unsupported reasoning / hallucination',`${pct(r.metrics.unsupportedReasoningRate)}; pre-registered maximum 10%. Measured as source-invalid quotations, unknown references or adjudicated relationship errors, including blocked outputs. Fabricated Evidence reference rate ${pct(r.metrics.fabricatedEvidenceReferenceRate)}. No unrestricted model summary: reasonSummary is software-rendered exact quoted evidence plus relationship. Cases with non-exact Evidence quotations: ${invalidQuotes}; cases with old support/context-role disagreement: ${oldRoleErrors}. Old support roles are preserved internally but are not explicitly labeled as currentRole in the model whitelist; the strict evaluator expects retained support roles. This representation/rubric mismatch contributes to errors and limits any blanket hallucination claim. The model also misjudges new-only impact and abstention. This narrowed metric does not certify arbitrary semantic entailment, unstated causal reasoning or real issuer generalization.`],
 ['Q. Forbidden investment judgment',`${pct(r.metrics.forbiddenInvestmentJudgmentRate)}; hard gate zero. Strict finite output contract and forbidden language scan also apply to model quotations; no Buy/Sell/Hold, targets, returns or allocations. Human review is knowledge-state review.`],
 ['R. Claims / Revisions protection','Both original v0.2-coreweave.sqlite and v0.4-recovery-final.sqlite are opened read-only, Claims=4 and Revisions=4 before/after, original claim payload hashes unchanged. Sources/Evidence/identities/revisions/corrections/Admission payload hashes are separately protected; every synthetic benchmark Memory snapshot also remains unchanged across reasoning.\n\n```json\n'+JSON.stringify(r.authorityProtection,null,2)+'\n```'],
 ['S. Paid API proof',`Paid inference API $0/calls0; paid embedding API $0/calls0. Local receipts: calls ${r.tokens.calls}, input ${r.tokens.input}, output ${r.tokens.output}, total ${r.tokens.total}. Loopback-only frozen provider, cloud disabled and remote guard; no warm-up or real smoke calls.`],
 ['T. Resource usage',`Offline development and fixture seeding, real inference only one locked benchmark. A failed first registration used Git-quoted Unicode paths: the shell briefly started an empty Ollama server before the failure was noticed; immediately stopped with zero model loads/inference. This process deviation is archived, not hidden. NUL-separated raw-byte baseline hashing fixed it before any locked inference. Successful gate: ${g.registeredAt}. Model started for the locked run only after successful registration and stopped afterward. `+(samples?`Sampled Ollama/runner RSS peak ${(Math.max(...samples.samples.map(s=>s.ollamaAndRunnerRssBytes))/1073741824).toFixed(2)} GiB on ${samples.cpu}, ${(samples.totalMemoryBytes/1073741824).toFixed(0)} GiB RAM; first sample ${samples.samples[0].at}; earliest cold-load peak may be excluded. `:'RSS unavailable. ')+`Median case end-to-end ${(median/1000).toFixed(2)} s, max ${(latencies.at(-1)/1000).toFixed(2)} s; includes impact call/validation/Proposal persistence, excludes offline fixture setup. caffeinate covers real run; no larger model, fine-tuning, continuous monitoring or parallel agents.`],
 ['U. Regression','Before inference: 145 agent tests and 21 Proposal tests (nine dev scenarios) PASS; syntax/frontend discipline/isolation and full verify-release PASS. After completion: 146 agent tests and 22 Proposal tests PASS, including exact locked gate/code/history/proposal/authority consistency; syntax, frontend discipline, development isolation and complete verify-release PASS. CSS unchanged, braces 2112/2112. All frozen baseline files are independently raw-byte SHA256 verified.'],
 ['V. End-to-end pending Proposal example',first?`${r.decision==='CLAIM REVISION PROPOSAL READY'?'Isolated pending demo uses a completed locked artifact.':'Gate not met: benchmark artifact shown for inspection only; no post-gate demo executed.'} Actual locked local-model output from ${first.caseId}, on an isolated synthetic existing Claim + system_test Accepted Evidence, stored independently and validated. Pending human review; no actual human review or Claim update. No extra model call.\n\n\`\`\`json\n${JSON.stringify({proposalId:first.proposal.proposalId,claimId:first.proposal.claimId,baseRevisionId:first.proposal.baseRevisionId,evidenceIds:first.proposal.evidenceIds,impact:first.proposal.impact,suggestedStatus:first.proposal.suggestedStatus,reasonCode:first.proposal.reasonCode,reasonSummary:first.proposal.reasonSummary,validation:first.validation,state:'pending',authoritativeRevisionWritten:false},null,2)}\n\`\`\``:'No valid locked Proposal; no demonstration asserted.'],
 ['W. Deliberately not implemented','Automatic Claim Revision, apply writer, LLM-Wiki, Thesis, Buy/Sell, portfolio recommendation, Multi-Agent, UI, deployment, continuous monitoring, cloud/larger-model tier, Replay backdating, generic finance semantic certification. This delivery stops at Proposal review.'],
 ['X. Decision',`**${r.decision}**. Safety pass=${r.safetyPass}; capability pass=${r.capabilityPass}. No post-run prompt/schema/config/threshold changes or exploratory reruns. `+(r.decision==='CLAIM REVISION PROPOSAL READY'?'A subsequent explicitly requested stage may consider knowledge projection or human review; this delivery does not start it.':'Remain on claim reasoning; no next-stage work. If reasoning, rather than deterministic plumbing, is the limitation, record LOCAL_MODEL_REASONING_LIMITATION before considering a new model tier. Input-role/evaluator agreement also needs review in a separately authorized iteration; no changes are made to this locked benchmark.')]
];
const lines=['# Claim Revision Proposal v0.12 — A–X delivery','',`**${r.decision}**`,'',...sections.flatMap(([title,body])=>['## '+title,'',body,'']), '## Locked per-case trace','', '|Case|Expected impact|Output impact|Valid Proposal|Impact correct|Attribution correct|Error|','|---|---|---|---|---|---|---|',...r.rows.map(x=>`|${x.caseId}|${x.expectedImpact}|${x.output?.impact??'null'}|${!!x.proposal}|${x.score.impactCorrect}|${x.score.attributionCorrect}|${x.error??'NONE'}|`)];
for(const path of ['docs/claim-revision-proposal-v0.12.md','research/claim-revision/DELIVERY.md'])writeFileSync(resolve(root,path),lines.join('\n')+'\n');
writeFileSync(resolve(art,'runtime-costs.json'),JSON.stringify({provider:r.provider,tokens:r.tokens,paidInferenceApiCostUsd:0,paidEmbeddingApiCostUsd:0,paidInferenceApiCalls:0,paidEmbeddingApiCalls:0,resource:r.resource,samples,latency:{medianCaseMs:median,maxCaseMs:latencies.at(-1)},registrationDeviation:read('registration-attempt-1').resourceDeviation},null,2)+'\n');
writeFileSync(resolve(art,'limitations.json'),JSON.stringify({decision:r.decision,reasoningLimitation:r.decision==='STAY ON CLAIM REASONING'?'LOCAL_MODEL_REASONING_LIMITATION':null,rawImpactMatches:rawImpactCorrect,strictImpactMatches:r.rows.filter(row=>row.score.impactCorrect).length,nonExactQuoteCases:invalidQuotes,oldRoleDisagreementCases:oldRoleErrors,oldRoleLabelNotExplicitInModelInput:true,rubricUnchanged:true,thresholdsUnchanged:true,noRetuningOrReruns:true,scope:'Narrow synthetic propositions; exact categories only; no arbitrary finance entailment or issuer generalization; role representation and strict rubric alignment require future independent work.'},null,2)+'\n');
console.log(r.decision);
