import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {stats} from '../local-retrieval/eval.js';
const root=fileURLToPath(new URL('../../',import.meta.url));
const read=n=>JSON.parse(readFileSync(resolve(root,'research/eval/selector-ranking',n+'.json'),'utf8'));
const r=read('results'),d=read('development'),g=read('phase-gate'),h=read('historical-metrics'),i=read('injection');
const pct=x=>x===null?'unavailable':(100*x).toFixed(2)+'%',fixed=x=>x===null?'unavailable':x.toFixed(4),m=r.metrics.ranked,b=r.retrievalBaseline;
const failures={};for(const row of r.rows)failures[row.failure]=(failures[row.failure]??0)+1;
const converted=r.rows.filter(x=>x.targetConverted),targetDepth=k=>converted.filter(x=>x.candidateFoundAtRank<=k).length;
const lines=['# v0.11.2 delivery report','', 'Decision: **'+r.decision+'**. No Claim Revision, deployment, release, or production push.','',
 '## A. Historical metric audit','',...Object.entries(h).map(([v,x])=>`${v}: ${x.selections} selections / ${x.targetHits} target hits / ${x.nonTargetSelections} non-target selections; precision ${pct(x.selectionPrecision)}, non-target rate ${pct(x.nonTargetSelectionRate)}, average ${x.averageSelections.toFixed(2)}. Historical relevance rank and Hit@1 unavailable.`),'',
 '## B. Retrieval-only ranking baseline','',`Locked K=8: Hit@1 ${pct(b.hitAtK[1])}, Hit@2 ${pct(b.hitAtK[2])}, Hit@3 ${pct(b.hitAtK[3])}, Hit@5 ${pct(b.hitAtK[5])}, Hit@8 ${pct(b.hitAtK[8])}, MRR ${fixed(b.mrr)}. Offline calculation; retrieval parameters unchanged. Full dev baselines in retrieval-only.json; exact-label comparison below.`,'',
 '## C. Files changed','',
 '- research/selector-ranking/REPOSITORY_AUDIT.md: pre-code inputs, per-case breadth, correlation, rank audit and label limitations.',
 '- research/selector-ranking/contract.js and ranking-output.schema.json: ordered unique dynamic handles, max 3, exact validation.',
 '- research/prompts/span-ranking-handles-v1.txt: one requested-fact ranking prompt.',
 '- research/selector-ranking/layer.js: isolated selection policies and bounded ordered interpretation/validation/Candidate fallback.',
 '- research/selector-ranking/cli.js: dev A/B/C and one registered locked policy, immutable-data replay, progress, resume, drift checks, cost/safety metrics.',
 '- research/selector-ranking/security.js: two guaranteed-exposure hostile-source fixtures, local receipts and Claims snapshots.',
 '- research/selector-ranking/audit.js: offline historical totals and retrieval metrics verification.',
 '- research/selector-ranking/README.md: local execution and resume instructions.',
 '- research/selector-ranking/report.js: deterministic result and A–U report rendering.',
 '- research/selector-ranking-test/contract.test.js, layer.test.js and artifacts.test.js: metrics, gate, exact handle validation, bounded fallback, support filtering.',
 '- agent/test/selector-ranking.test.js: runs ranking regressions in mandatory CI.',
 '- research/package.json: ranking CLI and test scripts.',
 '- research/eval/selector-ranking/*.json: historical metrics, baselines, development, pre-registration, injection, locked results.',
 '- docs/evidence-selector-ranking-v0.11.2.md and DELIVERY.md: rationale, measured outcomes and complete delivery.',
 'Frozen frontend, retrieval, grounding, support, validator, proposal, Admission, Claims and provider implementations: zero modifications. API version identifiers unchanged.','',
 '## D. Ranking contract','', '`{"rankedHandles":["S4","S7","S2"]}`; smallest ordered direct-support set; [] allowed. No confidence or canonical hashes.','',
 '## E. Dynamic handle schema','', '`ranked-handles/v1`: current available S1..S8 enum; maxItems 3, uniqueItems true, additionalProperties false; exact deterministic S→SourceSpan mapping, no fuzzy repair.','',
 '## F. Development A/B/C','', '|Arm, 17 exact answer-free positives|Hit@1|Hit@2|Hit@3|MRR|Precision|Average|Abstention|','|---|---:|---:|---:|---:|---:|---:|---:|',...Object.entries(d.metrics).map(([name,x])=>`|${name}|${typeof x.hitAtK==='object'?pct(x.hitAtK[1]):'unavailable'}|${typeof x.hitAtK==='object'?pct(x.hitAtK[2]):'unavailable'}|${typeof x.hitAtK==='object'?pct(x.hitAtK[3]):'unavailable'}|${typeof x.mrr==='number'?fixed(x.mrr):'unavailable'}|${pct(x.selectionPrecision)}|${x.averageSelectedHandles.toFixed(2)}|${pct(x.abstentionRate)}|`),'',
 'Two page-fallback labels and two negative queries without document targets are explicitly excluded from the exact positive comparison. Retrieval arm reports all K=8 rank entries; that breadth is not an LLM selection. Multi-select has no relevance ordering.','',
 '## G. Frozen policy','',`${g.promptVersion}; ${g.schemaVersion}; ${g.promptHash}. Registered ${g.registeredAt} before locked inference. Only ranked policy ×16 locked Gold. Require MRR uplift ≥${g.value.minimumAbsoluteMrrUplift} and Hit@1 uplift ≥${g.value.minimumAbsoluteHit1Uplift}; all safety and injection gates pass. Model qwen3.5:9b / Q4_K_M / non-thinking / temperature 0; unchanged digest, context 8192, 60 s call deadline; Hybrid K=8. Code and development hashes bind the run.`,'',
 '## H. Locked Hit@1 / Hit@2 / Hit@3','', `${pct(m.hitAtK[1])} / ${pct(m.hitAtK[2])} / ${pct(m.hitAtK[3])}. Compatibility target-anywhere hit ${pct(m.targetHitRate)}.`, '',
 '## I. MRR','',`Qwen ${fixed(m.mrr)} versus retrieval ${fixed(b.mrr)}; absolute uplift ${fixed(m.mrr-b.mrr)}. Hit@1 uplift ${pct(m.hitAtK[1]-b.hitAtK[1])}. Development and locked are separate evidence sets; no repeated locked runs or post-lock prompt tuning.`, '',
 '## J. Selection precision','',`${m.targetSelections}/${m.totalSelections} = ${pct(m.selectionPrecision)}; ${m.nonTargetSelections} non-target selections.`, '',
 '## K. Average selected handles','',`${m.averageSelectedHandles.toFixed(2)}; abstention ${pct(m.abstentionRate)}; hard output maximum 3.`, '',
 '## L. Rank-1 / Rank≤2 / Rank≤3 conversion','',`Any legal Candidate: ${r.conversion.rank1}/16 / ${r.conversion.rankLe2}/16 / ${r.conversion.rankLe3}/16. Gold target-semantic conversion: ${targetDepth(1)}/16 / ${targetDepth(2)}/16 / ${targetDepth(3)}/16. Total target conversion ${r.conversion.targetConverted}/16. An unrelated valid fact is never target success. targetScore preserves the existing pre-conversion scorer; outer targetConverted and candidateFoundAtRank are authoritative conversion fields.`, '',
 '## M. Retrieval miss','',r.rows.filter(x=>x.failure==='RETRIEVAL_MISS').map(x=>x.caseId).join(', ')||'None','',
 'GOLD-11 remains the frozen retrieval miss; no retrieval repair or tuning.','',
 '## N. Ranking miss and failure taxonomy','',JSON.stringify(failures), '',
 '## O. Latency','',`Ranking median ${(r.latency.ranking.median/1000).toFixed(2)} s / p95 ${(r.latency.ranking.p95/1000).toFixed(2)} s. Processing total median ${(r.latency.endToEnd.median/1000).toFixed(2)} s / p95 ${(r.latency.endToEnd.p95/1000).toFixed(2)} s, excluding offline retrieval. Historical frozen retrieval query median 33.17 ms / p95 228.95 ms (v0.11); current retrieval replay latency unavailable.`,...Object.entries(r.latency.interpretationByRank).map(([k,x])=>`Rank ${k} interpretation: ${x.count} calls; median ${x.median===null?'unavailable':(x.median/1000).toFixed(2)+' s'}, p95 ${x.p95===null?'unavailable':(x.p95/1000).toFixed(2)+' s'}.`),'',
 '## P. Token usage','',`Locked: ${r.tokens.calls} calls, input ${r.tokens.input}, output ${r.tokens.output}, total ${r.tokens.total}. Development: ${d.tokens.calls} calls, input ${d.tokens.input}, output ${d.tokens.output}. Injection: ${i.runs.reduce((n,x)=>n+x.receipts.length,0)} calls; per-call token and phase receipts in injection.json. Warm-up was not run; no unreported benchmark inference calls.`, '',
 ...['retrieval','multi','ranked'].map(policy=>{const rows=d.rows.filter(r=>r.policy===policy),receipts=rows.flatMap(r=>r.receipts),latency=stats(rows.map(r=>r.endToEndLatencyMs));return `Development ${policy}: ${receipts.length} model calls, input ${receipts.reduce((n,r)=>n+(r.usage?.inputTokens??0),0)}, output ${receipts.reduce((n,r)=>n+(r.usage?.outputTokens??0),0)}; offline processing median ${latency.median.toFixed(2)} ms. Retrieval arm processing is cached-rank lookup, not new retrieval query latency.`;}), '',
 '## Q. Safety','',JSON.stringify(r.safety),`Injection passed: ${i.passed}. All offered/selected supports preserve exact identities; converted facts are rechecked with unchanged support/fact validators. No provider errors tolerated for readiness. Historical evaluator Gold-prioritized promotion and fixed-zero false-accept summaries remain unchanged; current strict ranking and contract rechecks do not use Gold for fallback or admission.`, '',
 '## R. Claims protection','',`Locked Claims unchanged: ${r.claimsProtection.unchanged}; injection unchanged: ${i.claimsProtection.unchanged}. Read-only identity/revision snapshots prove integrity. No Admission or Evidence writes.`, '',
 '## S. Paid API proof','',`paidInferenceApiCostUsd=${r.paidInferenceApiCostUsd}; paidEmbeddingApiCostUsd=${r.paidEmbeddingApiCostUsd}; paidInferenceApiCalls=0; paidEmbeddingApiCalls=0. Only loopback Ollama transport with remote guard, no cloud inference or new embedding calls.`, '',
 '## T. Regression','', 'Eight ranking regressions; exact resolution/schema, honest metrics, value/safety decision, hidden canonical IDs, ordered fallback, hard rank-3 stop and wrong-subject/future rejection. Mandatory syntax, frontend discipline, isolation, agent tests and verify-release gates run; 117 agent tests and 8 focused ranking tests passed; full verify-release gate passed. CSS unchanged; brace balance checked. No frozen-area edits.','',
 '## U. Decision','', '**'+r.decision+'**. '+(r.decision==='SELECTOR READY'?'The registered MRR and Hit@1 uplifts pass on locked evidence, confirming independent development ranking gains; safety and injection hard gates pass. Keep ranking in the research architecture where it adds measured discrimination. This is a small exploratory benchmark, not production rollout authorization.':r.decision==='BYPASS LLM SELECTOR'?'Retrieval ranking meets or exceeds Qwen on both primary measures; bypass removes an extra model call and error surface.':'The pre-registered evidence does not establish sufficient selector value. Keep calibrating without claiming readiness.'),'',
 '## Locked case details','', '|Case|Target rank in retrieval|Target rank in Qwen|Selected|Candidate rank|Target converted|Failure|','|---|---:|---:|---:|---:|---:|---|',...r.rows.map(x=>{const rank=ids=>{const at=ids.findIndex(id=>x.expectedSpanIds.includes(id));return at<0?'miss':at+1;};return `|${x.caseId}|${rank(x.retrievedSpanIds)}|${rank(x.selectedSpanIds)}|${x.selectedSpanIds.length}|${x.candidateFoundAtRank??'null'}|${x.targetConverted?'yes':'no'}|${x.failure}|`;})];
writeFileSync(resolve(root,'research/selector-ranking/DELIVERY.md'),lines.join('\n')+'\n');
const doc=resolve(root,'docs/evidence-selector-ranking-v0.11.2.md'),source=readFileSync(doc,'utf8').split('\n## Locked outcome\n')[0];
writeFileSync(doc,source+'\n## Locked outcome\n\n'+lines.slice(lines.indexOf('## H. Locked Hit@1 / Hit@2 / Hit@3')).join('\n')+'\n');
writeFileSync(resolve(root,'research/eval/selector-ranking/runtime-costs.json'),JSON.stringify({version:'selector-ranking-runtime-costs/v0.11.2',provider:r.provider,development:d.tokens,locked:r.tokens,injection:{calls:i.runs.reduce((n,x)=>n+x.receipts.length,0),input:i.runs.flatMap(x=>x.receipts).reduce((n,x)=>n+(x.usage?.inputTokens??0),0),output:i.runs.flatMap(x=>x.receipts).reduce((n,x)=>n+(x.usage?.outputTokens??0),0)},latency:r.latency,paidInferenceApiCostUsd:0,paidEmbeddingApiCostUsd:0,paidInferenceApiCalls:0,paidEmbeddingApiCalls:0,note:'Existing local loopback-only provider. No embedding inference in this phase; cached rank replay. Hardware/electricity are not free; not monetized here.'},null,2)+'\n');
console.log(r.decision);
